"use client";

import { useState } from "react";
import { PDFDocument } from "pdf-lib";
import { DownloadButton } from "./download-button";
import { FileDrop, MAX_IMAGE_SIZE, MAX_PDF_SIZE, validSize } from "./file-drop";
import { CompletedTracker } from "@/components/dashboard/usage-tracker";

async function bytes(file: File) { return new Uint8Array(await file.arrayBuffer()); }

function pdfBlob(data: Uint8Array) {
  // Copy into a fresh ArrayBuffer so newer TypeScript DOM typings do not
  // treat pdf-lib's ArrayBufferLike-backed Uint8Array as a SharedArrayBuffer.
  const copy = new Uint8Array(data.byteLength);
  copy.set(data);
  return new Blob([copy.buffer], { type: "application/pdf" });
}

function msgForFile(file: File, max: number) { if (!validSize(file,max)) return `File is too large. Maximum is ${max/1024/1024} MB.`; return ""; }

export function JpgToPdf() { const [files,setFiles]=useState<File[]>([]);const [blob,setBlob]=useState<Blob|null>(null);const [error,setError]=useState("");return <div className="space-y-5"><CompletedTracker toolSlug="jpg-to-pdf" enabled={blob !== null}/><FileDrop accept="image/jpeg,image/png,image/webp" multiple onFiles={fs=>{const bad=fs.find(f=>!f.type.startsWith("image/")||!validSize(f,MAX_IMAGE_SIZE));setError(bad?"Only supported images under 20 MB are allowed.":"");setFiles(bad?[]:fs);setBlob(null);}}/><p className="text-sm text-[var(--muted)]">Images are processed locally. Each image must be under 20 MB.</p>{files.length>0&&<p className="text-sm">{files.length} image(s) selected.</p>}<button type="button" disabled={!files.length} className="rounded-xl bg-indigo-600 px-5 py-3 text-sm font-bold text-white disabled:opacity-50" onClick={async()=>{const pdf=await PDFDocument.create();for(const f of files){const b=await bytes(f);let img;if(f.type==="image/jpeg")img=await pdf.embedJpg(b);else if(f.type==="image/png")img=await pdf.embedPng(b);else {const url=URL.createObjectURL(f);try{const image=new Image();image.src=url;await image.decode();const canvas=document.createElement("canvas");canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;canvas.getContext("2d")?.drawImage(image,0,0);const png=await new Promise<Uint8Array>((resolve,reject)=>canvas.toBlob(async x=>x?resolve(new Uint8Array(await x.arrayBuffer())):reject(new Error("Conversion failed")),"image/png"));img=await pdf.embedPng(png);}finally{URL.revokeObjectURL(url);}}const page=pdf.addPage([img.width,img.height]);page.drawImage(img,{x:0,y:0,width:img.width,height:img.height});}setBlob(pdfBlob(await pdf.save()));}} >Create PDF</button><DownloadButton blob={blob} filename="toolnest-images.pdf"/>{error&&<p className="text-sm text-red-600">{error}</p>}</div>; }

export function PdfMerge() { const [files,setFiles]=useState<File[]>([]);const [blob,setBlob]=useState<Blob|null>(null);const [error,setError]=useState("");return <div className="space-y-5"><CompletedTracker toolSlug="pdf-merge" enabled={blob !== null}/><FileDrop accept="application/pdf" multiple onFiles={fs=>{const bad=fs.find(f=>f.type!=="application/pdf"||!validSize(f,MAX_PDF_SIZE));setError(bad?"Only PDF files under 50 MB each are allowed.":"");setFiles(bad?[]:fs);setBlob(null);}}/><p className="text-sm text-[var(--muted)]">Files stay in your browser. Maximum 50 MB per PDF.</p><button type="button" disabled={!files.length} className="rounded-xl bg-indigo-600 px-5 py-3 text-sm font-bold text-white disabled:opacity-50" onClick={async()=>{const out=await PDFDocument.create();for(const f of files){const doc=await PDFDocument.load(await bytes(f));const pages=await out.copyPages(doc,doc.getPageIndices());pages.forEach(p=>out.addPage(p));}setBlob(pdfBlob(await out.save({useObjectStreams:true})));}}>Merge PDFs</button><DownloadButton blob={blob} filename="toolnest-merged.pdf"/>{error&&<p className="text-sm text-red-600">{error}</p>}</div>; }

export function PdfSplit() { const [file,setFile]=useState<File|null>(null);const [page,setPage]=useState(1);const [end,setEnd]=useState(1);const [blob,setBlob]=useState<Blob|null>(null);const [count,setCount]=useState(0);const [error,setError]=useState("");return <div className="space-y-5"><CompletedTracker toolSlug="pdf-split" enabled={blob !== null}/><FileDrop accept="application/pdf" onFiles={async fs=>{const f=fs[0];if(!f)return;const e=msgForFile(f,MAX_PDF_SIZE);if(e){setError(e);return;}const doc=await PDFDocument.load(await bytes(f));setFile(f);setCount(doc.getPageCount());setEnd(doc.getPageCount());setBlob(null);setError("");}}/><p className="text-sm text-[var(--muted)]">Select a page range from the PDF. Maximum 50 MB.</p>{file&&<><p className="text-sm">Pages: <b>{count}</b></p><div className="grid gap-4 sm:grid-cols-2"><label>From<input className="mt-2 w-full rounded-xl border p-3 bg-[var(--background)]" type="number" min="1" max={count} value={page} onChange={e=>setPage(Number(e.target.value))}/></label><label>To<input className="mt-2 w-full rounded-xl border p-3 bg-[var(--background)]" type="number" min="1" max={count} value={end} onChange={e=>setEnd(Number(e.target.value))}/></label></div><button type="button" className="rounded-xl bg-indigo-600 px-5 py-3 text-sm font-bold text-white" onClick={async()=>{if(page<1||end>count||page>end){setError("Choose a valid page range.");return;}const src=await PDFDocument.load(await bytes(file));const out=await PDFDocument.create();const pages=await out.copyPages(src,Array.from({length:end-page+1},(_,i)=>page-1+i));pages.forEach(p=>out.addPage(p));setBlob(pdfBlob(await out.save({useObjectStreams:true})));setError("");}}>Split / extract pages</button><DownloadButton blob={blob} filename="toolnest-split.pdf"/></>}{error&&<p className="text-sm text-red-600">{error}</p>}</div>; }

export function PdfCompressor() { const [file,setFile]=useState<File|null>(null);const [blob,setBlob]=useState<Blob|null>(null);const [error,setError]=useState("");return <div className="space-y-5"><CompletedTracker toolSlug="pdf-compressor" enabled={blob !== null}/><FileDrop accept="application/pdf" onFiles={fs=>{const f=fs[0];if(!f)return;const e=msgForFile(f,MAX_PDF_SIZE);setError(e);setFile(e?null:f);setBlob(null);}}/><p className="text-sm text-[var(--muted)]">ToolNest rebuilds the PDF using compact object streams. This can reduce structural overhead; image-heavy PDFs may not shrink substantially without rasterizing pages.</p>{file&&<button type="button" className="rounded-xl bg-indigo-600 px-5 py-3 text-sm font-bold text-white" onClick={async()=>{const doc=await PDFDocument.load(await bytes(file));setBlob(pdfBlob(await doc.save({useObjectStreams:true,addDefaultPage:false})));}}>Optimize PDF</button>}<DownloadButton blob={blob} filename="toolnest-optimized.pdf"/>{blob&&file&&<p className="text-sm text-[var(--muted)]">Original: {(file.size/1024).toFixed(1)} KB · Output: {(blob.size/1024).toFixed(1)} KB</p>}{error&&<p className="text-sm text-red-600">{error}</p>}</div>; }
